### ISSUE TITLE
breadcrumb fix blocks CSS colors

### ISSUE THREAD

**Issue by dennisns7d** [lat9/ZCA-Bootstrap-Template#109]
The breadcrumb fix disables the CSS for breadcrumbs since the ordered list is no longer generated. The includes/templates/bootstrap/css/stylesheet_zca_colors.php needs to be adjusted to apply the desired colors. Perhaps:
`#navBreadCrumb {background-color: <?php echo ZCA_BODY_BREADCRUMBS_BACKGROUND_COLOR; ?>;}
#navBreadCrumb {color: <?php echo ZCA_BODY_BREADCRUMBS_TEXT_COLOR; ?>;}
#navBreadCrumb a {color: <?php echo ZCA_BODY_BREADCRUMBS_LINK_COLOR; ?>;}
#navBreadCrumb a:hover {color: <?php echo ZCA_BODY_BREADCRUMBS_LINK_COLOR_HOVER; ?>;}
`

Padding and margins should also be added to the <div to approximate what the bootstrap breadcrumb class applied to the ordered list. This could be done either via specifying the appropriate classes on the <div (py-2 px-3 mb-3) or by adding a rule to stylesheet.css with padding and margin-bottom values copied from bootstrap.css. Using class="breadcrumb" appears to work.

**Comment by lat9** [comment]
Closing this as it's associated with the forthcoming correction for #108.
