### ISSUE TITLE
WCAG compliance - change from <ol> in breadcrumb

### ISSUE THREAD

**Issue by OldNGreyBMR** [lat9/ZCA-Bootstrap-Template#116]
For WCAG compliance `<ul> and <ol> must only directly contain <li>, <script> or <template> elements`

 In 
 includes\templates\bootstrap\common\tpl_main_page.php  line 153 
 I removed ol and li from breadcrumbs and reverted to  the version in the standard template.
 

  ```
  <div id="navBreadCrumb">
                <ol class="breadcrumb">
                    <?php echo $breadcrumb->trail(BREAD_CRUMBS_SEPARATOR, '<li>', '</li>'); ?>
                </ol>
  </div>
  ```
     
   to

   ```
<div id="navBreadCrumb">
                    <?php echo $breadcrumb->trail(BREAD_CRUMBS_SEPARATOR); ?>
    </div>
 ```

**Comment by lat9** [comment]
Already changed via issue #108.
