### ISSUE TITLE
No Mention of Data Loss on Upgrade?

### ISSUE THREAD

**Issue by dbltoe** [lat9/ZCA-Bootstrap-Template#119]
Here's the scenario:
Site with 1.5.6c and many mods using responsive_classic.  Busy site needing minimal downtime while upgrading.

Steps:
Loaded 1.5.7d in a test folder and installed all current versions of the many mods.  Also installed 3.3.0 of bootstrap.
Adjusted all the colors to meet or exceed ADA/WCAG contrast standards.  (figured doing this before bringing in the old database would keep downtime to a minimum)
Deleted the existing DB, imported the old DB, and ran the DB update.

Assumption:
Since bootstrap was not part of the site, I thought my settings would remain intact.  NOPE.

Resolution?
Falsely thinking the color settings would remain, I did not back up the settings.  I wound up having to do a major restore.  And, still was not sure how to get my settings into the updated DB.
Should something be added to the docs about how to save settings in this type of scenario?  If I had been thinking properly, I would have backed up the colors.
How about adding info on retaining colors setup prior to DB import/upgrade?  Maybe add a .sql file to assist in keeping the settings on upgrade?
I don't think I uploaded the colors separately but, a lot of busy stuff around here these days.

**Comment by lat9** [comment]
The "ZCA Bootstrap Colors" tool has the capability of exporting and importing the color settings:
![image](https://user-images.githubusercontent.com/2685585/162952812-96dc1e2c-4ab7-424d-9235-3cf95a8501fb.png)

**Comment by dbltoe** [comment]
That must have been in a different area of my trifocals. :grin:

THANX
