### ISSUE TITLE
Restore 'base' Zen Cart attributes HTML class and id attributes

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#120]
The layout of the attributes block in the template has
1. Changed the HTML `id` attribute of the overall container to `productInfo-productAttributes` instead of `productAttributes`.
2. The 'card' rendered for each options' selection is missing the `wrapperAttribsOptions` class.

This causes an incompatibility with at least one plugin that 'expects' the layout to have those HTML attributes present.

**Comment by dennisns7d** [comment]
Might it be appropriate to make similar changes to tpl_document_general_info_display.php, tpl_document_product_info_display.php, tpl_product_free_shipping_info_display.php, and tpl_product_music_info_display.php?

**Comment by lat9** [comment]
Ah, yes.  Thanks for the heads-up.

**Comment by lat9** [comment]
Updates now provided!
