### ISSUE TITLE
small refactor

### ISSUE THREAD

**Issue by proseLA** [lat9/ZCA-Bootstrap-Template#122]
could the following code:
https://github.com/lat9/ZCA-Bootstrap-Template/blob/06db1914f2e3c2ce26ce3734d32b162e8618e862/includes/templates/bootstrap/templates/tpl_account_history_info_default.php#L141-L148

be refactored to:
```
               if (!empty($statuses['comments'])) {
                    echo nl2br(zen_output_string($statuses['comments'], false, $first));
                    if ($first) {
                        $first = false;
                    }
                }
```

more curiosity than anything...

**Comment by lat9** [comment]
What's the 'motivation' and/or use-case for the change?  I'm trying to keep the basic 'Bootstrap' processing as close to the base Zen Cart's to make it easier to incorporate any Zen Cart base changes.

**Comment by proseLA** [comment]
i see it in the base code as well.  so i get your point.

use case would be if the comments were valid html, and one wanted to output them as such, ie not running them through the `zen_output_string` method.  and now would be delving further into the arrow anti-pattern.  ie, there would be an additional conditional if the comments were valid html and wanted them output as such.  but now one would need to check if first as well within that if as well as within the else.

it's really just a rhetorical question more than anything.  as well as style.  i prefer less conditionals and examining fewer methods when figuring out what things are doing.
