### ISSUE TITLE
ZC158: includes\modules\pages\account_history\header_php.php - $accountHasHistory does not exist

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#123]
..leading to debugs.
In any case perhaps
`if ($accountHasHistory && function_exists('zca_bootstrap_active') && zca_bootstrap_active()) {`
should be
`if (function_exists('zca_bootstrap_active') && zca_bootstrap_active() && $accountHasHistory/equivalent) {`
would prevent errors until the template was in use/being developed.

**Comment by lat9** [comment]
Thanks for the report, @torvista

**Comment by lat9** [comment]
Closing, now that the variable has been resurrected in the above zc158 merge.
