### ISSUE TITLE
Branch for ZC158?

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#127]
I'm finally about to start on a new template saga starting with this and so will be reviewing the changes for ZC158.
While I could start one off my fork, do you have a better procedure?

**Comment by lat9** [comment]
For the zc158 support, I'll be 'trying' to keep a single branch that supports both zc157 and zc158.  For now, how about just reports of inconsistencies when the current branch is used on zc158?

**Comment by torvista** [comment]
ok

**Comment by lat9** [comment]
Understood; as always I appreciate your support and will use your fork as a basis for the zc158 changes going forward!

**Comment by lat9** [comment]
See #134.  That details all the changes needed for the zc158 integration.  It should be an aid to other template authors as a guide to the various changes needed.
