### ISSUE TITLE
Information sidebox, enabling quick overrides for about-us/brands inclusion

### ISSUE THREAD

**Issue by dennisns7d** [lat9/ZCA-Bootstrap-Template#154]
I noticed this [post ](https://www.zen-cart.com/showthread.php?223910-ZCA-Bootstrap-4-Template-Support-Thread&p=1390970#post1390970)in the support forum a bit over a week ago. Since I didn't see a response in the forum, I thought it wise to post here so that it doesn't slip through the cracks.

**Comment by lat9** [comment]
Changing to a bug, since this was needed for a zc158 integration.
