### ISSUE TITLE
Warning when Opening Document - General 

### ISSUE THREAD

**Issue by dbltoe** [lat9/ZCA-Bootstrap-Template#163]
Bootstrap 4.3.1 latest version (tried both plain load and our clone)
Zen Cart 158
PHP 7.4 thru 8.1  (no difference with any PHP)
Error does not occur with plain Responsive_Classic

Created Category "DVD"

Restricted Category to Document General and saved without subdirectories

Added Document - General item "DVD"

DVD is now displayed in the Documents sidebox on the main page.

Clicking on "DVD" in the Documents sidebox throws a warning.

`[29-Nov-2022 13:11:39 America/Denver] Request URI: /index.php?main_page=document_product_info&cPath=301&products_id=642, IP address: 225.225.225.225, Language id 1
#1 require(/includes/templates/boot_horn/templates/tpl_document_product_info_display.php) called at [/includes/modules/pages/document_product_info/main_template_vars.php:153]
#2 require(/includes/modules/pages/document_product_info/main_template_vars.php) called at [/includes/templates/boot_horn/common/tpl_main_page.php:202]
#3 require(/includes/templates/boot_horn/common/tpl_main_page.php) called at [/index.php:94]
--> PHP Warning: Undefined variable $one_time in /includes/templates/boot_horn/templates/tpl_document_product_info_display.php on line 241.`

**Comment by lat9** [comment]
Dang it; the same will occur for all product types _other than_ **Product - General**.

**Comment by dbltoe** [comment]
Works for us.

THANX
