### ISSUE TITLE
Remove /jscript/jquery.min.js from the distribution

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#168]

**Comment by lat9** [comment]
I'm thinking that it makes no sense to provide a means to load the jQuery core if it's not loaded via the CDN since it's likely that the load will also fail for the bootstrap css/js and font-awesome CDNs as well.

**Comment by lat9** [comment]
Added the 'documentation' label so that I don't forget to update the Bootstrap/FA versions in the readme.md file.

**Comment by torvista** [comment]
I never understood why not every cdn-loaded file does have a local fallback.

**Comment by lat9** [comment]
I think (keyword) that it was to enable unconnected-to-the-internet testing, modeled after `responsive_classic` which only pulls in jQuery.

**Comment by torvista** [comment]
I used to be forced to work offline for weeks, and had everything duplicated locally.
But still, in production, it should be all or nothing. No point being partially prepared.
