### ISSUE TITLE
update of CDN links?

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#169]
I note that there are newer versions of all these preloads.
https://github.com/lat9/ZCA-Bootstrap-Template/blob/8be8e62453e9aa561221331ce2cecf8957f19436/includes/templates/bootstrap/common/html_header.php#L33-L48

Any reasons to not use them yet?
I'm trying them out.

**Comment by lat9** [comment]
Me, too.  So far so good, although this will cause the next release to bump the middle version (i.e. v3.5.0 instead of v3.4.2) since it's a fair change.

**Comment by lat9** [comment]
Added the 'documentation' label so that I don't forget to update the Bootstrap/FA versions in the readme.md file.

**Comment by lat9** [comment]
That update to jQuery 3.6.0 kind of scares me; I'm not sure what (if any) gremlins it will open.  I'll note that the updated version of Bootstrap indicates that it was tested with jQuery 3.5.1, which makes me even more hesitant.

**Comment by torvista** [comment]
>the updated version of Bootstrap indicates that it was tested with jQuery 3.5.1, which makes me even more hesitant.
Agreed.
