### ISSUE TITLE
HTML validation: Buttons can't be descendents of anchor tags

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#183]
![image](https://user-images.githubusercontent.com/2685585/208248624-3fffb3f9-4326-4c7c-9466-aacebe141f55.png)

![image](https://user-images.githubusercontent.com/2685585/208248595-65d22fad-ad19-4497-9685-c075638ec587.png)

**Comment by lat9** [comment]
Sigh, this is pervasive.

**Comment by dbltoe** [comment]
Is it possible to give all occurrences a particular class?  If so,

`<a class="p-1" href="[https://myzencarttemplates.com/index.php?main_page=product_info&amp;cPath=22&amp;products_id=7](https://myzencarttemplates.com/index.php?main_page=product_info&cPath=22&products_id=7)"><button type="button" class="btn button_prev">Previous</button></a>` 

could become 

`<a class="p-1 btnSpecial" href="[https://myzencarttemplates.com/index.php?main_page=product_info&amp;cPath=22&amp;products_id=7](https://myzencarttemplates.com/index.php?main_page=product_info&cPath=22&products_id=7)">Previous</button></a>`

for each occurrence.

Then you would need to use the CSS to make the anchor look like a button.  display: inline-block to make the button fit the text.  Might need a nowrap but not sure.  Even having to create several classes to avoid all button colors being controlled in one place, it would at least satisfy both Accessibility and HTML.

**Comment by lat9** [comment]
That's essentially what I've got coming up, using a bootstrap-specific function so that all the non-submit type buttons will be rendered in a similar manner, using the Bootstrap `.btn` class on the anchor.

**Comment by lat9** [comment]
Sheesh, that was pretty-much all of the template files!
