### ISSUE TITLE
Product with attributes: why two price blocks?

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#186]
![2022-12-18 22_03_02-Matrox G200 MMS  MG200MMS  - $299 99 _ Zen Cart!, The Art of E-commerce — Mozill](https://user-images.githubusercontent.com/4391026/208319317-406cad61-0a7f-4475-a494-296402d32856.gif)

**Comment by lat9** [comment]
Erm, because some of the attribute lists (e.g. Bug's life linked in the demo products) go on FOREVER?  I'm open to removing the bottom one, depending on push-back.

**Comment by torvista** [comment]
While I'll fettle with code, "design" things are for others to argue about. 
One or the other is easily hidden.

One design aspect is that is glaringly lacking is the attribute price not updating with attribute changes. That should be core.
