### ISSUE TITLE
shopping-cart: Delete checkboxes and icons don't display on small screens ...

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#194]
... leading to customer confusion &mdash; not a good thing.

Replicate the icon/checkboxes underneath the quantity input for each product on small screens only.

**Comment by lat9** [comment]
@dbltoe, I'm a bit concerned that the current implementation for this might 'confuse' screen-readers, since there could now be two icons/checkboxes per product associated with its removal from the cart.  Please advise.

**Comment by dbltoe** [comment]
Just got in from a trip.  I'll look as soon as I can.

**Comment by dbltoe** [comment]
My personal opinion is that the checkbox is not needed, could cause accidental deletion, and would need some explanation to the user as to what the box is accomplishing.

Isn't it like adding an extra step?  If I wanted to delete two or more items from a cart, why take the time to go down the list and check them _and then_ go to the spinning circle or trash can to delete them?  Why not just click on the can?  There are going to be mistakes made either way but correcting one inadvertent click is a lot easier if it only affected one item.

As far as pure accessibility, the items are too close for the fat-fingered among us.  That's the first accessibility hit but not the worst by far.

In true accessibility terms, a check box actually has three "states" in this scenario.  True, False, or Mixed.  Adding the checkbox to perform this role (role="checkbox") also adds the requirement to notify the readers of the current state of each box by including an "aria-checked" attribute that specifies which of the three states is current.

You might get away with not doing all the states and the aria-checked attribute IF you were to use radio buttons in place of the checkboxes as they do not support the mixed state value. They would not need the extra attribute.  However, they would still be too close to the can.

IMHO, I would not use anything but the can icon.  The simple act of scrolling with their finger could be a problem. I think this may be a fix in search of a "maybe" need that winds up being a major coding nightmare.  I would not use the checkbox in either mode.

I'm also trying to verify, but something in there is breaking the responsive action of the cart in my mobile simulator.

**Comment by lat9** [comment]
I'll note that the presence of the checkbox is 'dictated by' the configuration setting `Stock :: Show Shopping Cart - Delete Checkboxes or Delete Button`.   Issue #193 addressed the fact that the template was not rendering what was configured.

I'll add some additional spacing between the quantity-input and the icon and/or checkbox for the small-width layout for the 'visual' among us, but my initial question still stands:

> Will screen-readers get 'confused', since there will now be two icons and/or checkboxes per product associated with its removal from the cart.

**Comment by lat9** [comment]
Margin added and the shopping-cart table now uses the `table-sm` class to cut down on inside-table padding, making more room for product-related information on the small screens.
