### ISSUE TITLE
Bootstrap Colors: Modify install/upgrade process for easier insertion/re-ordering of color elements

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#211]
This functionality is needed to support the addition and modification of colors required by #210.  It will add another (hidden) configuration setting so that the "ZCA Bootstrap Colors" configuration settings can now be versioned, making it easier when future updates are required.

**Comment by dennisns7d** [comment]
As a test case for adding colors, please consider adding:

- The Add to Cart icon in the Order History sidebox (class="fas fa-cart-plus").
- The checkout button (class="btn button_checkout").
- The continue checkout button (class="btn button_continue_checkout").
- The confirm order button (class="btn button_confirm_order").

 IMO the color of the Add to Cart icon in the Order History sidebox should be consistent with the Add to Cart buttons displayed elsewhere.

IMO the color of the checkout process buttons should contrast with the other buttons on the checkout pages to help lead a customer through the process.

**Comment by lat9** [comment]
Good points, @dennisns7d.  @dbltoe, do you have any color suggestions for the elements identified above?

**Comment by lat9** [comment]
Note, too, that I'm using PR #208 as the basis for the initial color changes/additions.

**Comment by lat9** [comment]
I'm not liking how the additional colors that 'need' to have default values assigned are currently being handled.  In the admin, they're initialized to 'not-set', but the storefront overrides that setting ... not good.

**Comment by lat9** [comment]
OK, that's better.  The storefront shouldn't have been overriding what was configured in the admin.
