### ISSUE TITLE
Alerts not showing standard Bootstrap colors

### ISSUE THREAD

**Issue by dennisns7d** [lat9/ZCA-Bootstrap-Template#213]
With the current work to restructure the color system, I reviewed my additions to `css/stylesheet_colors.css`. I had added rules for `.alert.alert-success` and `.alert.alert-info` to set `color:` to the values in `bootstrap.css`. I didn't initially recall why.

In reviewing today's commits for `css/stylesheet_zca_colors.php`, I thing I found the "why". The current version contains `.alert {color: <?php echo ZCA_BODY_PLACEHOLDER; ?>;}`.

`bootstrap.css` sets the colors in rules for `.alert-success`, `alert-info`, etc. Since `css/stylesheet_zca_colors.php` is loaded, its `.alert` rule takes precedence.

IMO, the `.alert` rule should be removed from `css/stylesheet_zca_colors.php`. Success and Info alerts just don't look right with RED letters.

**Comment by dbltoe** [comment]
A lot of the colors do not look well together on a page but are done as they are to assist the user in locating them among the many color combinations.  That way the store owner can easily find them and adjust them to their particular color scheme.

At least for my part, there was no attempt to make the colors "flow" or follow any pattern other than a contrast of 7.5:1 on the colors.  There was no thought to "purdy" involved in the process. 😃

**Comment by dennisns7d** [comment]
Are the alert `background-color` values being checked against `ZCA_BODY_PLACEHOLDER` values?

**Comment by lat9** [comment]
FWIW, I'm planning on changing that overall `.alert` class' styling to `span.alert` so it's not so _greedy_.

**Comment by dennisns7d** [comment]
That should handle `TEXT_COUPON_FAILED`: `<span class="alert important">`

A few other places to check:

- includes/modules/payment/square.php: `<div id="card-errors" class="alert error">`
- includes/templates/bootstrap/templates/tpl_create_account_register.php: `<div class="alert forward">`
- includes/modules/pages/checkout_payment/jscript_square.php: `<p class="error alert">`
