### ISSUE TITLE
Remove in-line color classes from templates

### ISSUE THREAD

**Issue by dennisns7d** [lat9/ZCA-Bootstrap-Template#215]
A few more potential trouble areas can be found by searching for `bg-success`, `bg-primary`, and `badge-primary` in the Catalog files.

For example, the use of `bg-success` in `tpl_address_book_default.php` fails the ANDI contrast check. The use of `bg-primary` passes the AA large text check, but not the AAA criteria.

**Comment by lat9** [comment]
... and on the 3-page checkout pages' progress-bars (arggh).

**Comment by lat9** [comment]
Affected `/template` files:
- tpl_address_book_default.php
- tpl_create_account_success_default.php
- tpl_modules_checkout_address_book.php

Affected `/sideboxes` files
- tpl_document_categories.php

**Comment by lat9** [comment]
Those 3 address-related template files will require additional color-configuration settings:

- `ZCA_PRIMARY_ADDRESS_ADDRESS_BACKGROUND_COLOR`, currently `.bg-success`
- `ZCA_PRIMARY_ADDRESS_ADDRESS_COLOR`, currently `.text-white`
- `ZCA_PRIMARY_ADDRESS_CARD_HEADER_BACKGROUND_COLOR`, currently `.bg-primary`
- `ZCA_PRIMARY_ADDRESS_CARD_HEADER_COLOR`, currently `.text-white`
- `ZCA_PRIMARY_ADDRESS_CARD_BORDER_COLOR`, currently `border-primary`.
