### ISSUE TITLE
Colors Not Showing Correctly in Admin

### ISSUE THREAD

**Issue by dbltoe** [lat9/ZCA-Bootstrap-Template#217]
A look at just a few of the colors at the start of the bootstrap colors from Tools.

![image](https://user-images.githubusercontent.com/5122886/220423253-a87c5643-7813-4c66-9754-7981e40c4426.png)

Not quite getting that the not set is not consistent.

![image](https://user-images.githubusercontent.com/5122886/220423591-e91085a2-150e-4b36-b644-6ec41e3a2700.png)

I'll reread the instructions again to make sure I didn't screw something up.

This was the very latest 1.5.8 with only bootstrap.

**Comment by lat9** [comment]
That's because you'd updated a previous beta of 3.5.2, so the more-recently added colors will show as 'not-set'.

**Comment by dbltoe** [comment]
I was trying to see what would happen on upgrade.
What confuses me is the first five colors show only two defaults and none designated set while the two in the second group with the two checkmarks actually indicate that one is not set.

Should I blow away all  semblance of bootstrap and start fresh?  Dropping the colors from the DB makes it even wonkier.

**Comment by lat9** [comment]
There's an uninstall-colors SQL file now in /docs/uninstall, just copy/paste the configuration values' DELETE to start over.

**Comment by dbltoe** [comment]
Had to refresh home several times to get it to work even after the uninstall.

NOTE:  Body Rating Stars Background Color should be #000000
Ezpage colors should be the same for header and footer but something in preventing the color change on hover.
![image](https://user-images.githubusercontent.com/5122886/220660910-61700948-93af-4c4f-aa58-5f866768e3dd.png)
It looks like the call for the header and footer backgrounds on hover are not present I.

It should be a simple swap of colors on hover.

![image](https://user-images.githubusercontent.com/5122886/220664143-b9ca0fde-37a7-4886-8beb-833ff1d7082c.png)
There should only be a max of three colors for the active link in the cat tabs.
Active is either off or on.  There is no hover required or suggested to identify it on hover.
The border and text color should be #ad3000 while the background should be #fffffff

Again, I can't get it to work as I find no call the CSS.

Apologies that I am not able to be more specific but I have been banned from the computer till health issues are better resolved

I hope to be back next week.  Thanks for all you have done.

**Comment by lat9** [comment]
To do a 'color-reset', you need to remove not only the colors, but also the colors' current version, as indicated in the uninstall SQL:
```
DELETE FROM configuration
 WHERE configuration_key = 'ZCA_BOOTSTRAP_COLORS_VERSION'
    OR configuration_key LIKE 'ZCA_BODY_%'
    OR configuration_key LIKE 'ZCA_BUTTON_%'
    OR configuration_key LIKE 'ZCA_HEADER_%'
    OR configuration_key LIKE 'ZCA_FOOTER_%'
    OR configuration_key LIKE 'ZCA_SIDEBOX_%'
    OR configuration_key LIKE 'ZCA_CENTERBOX_%'
    OR configuration_key LIKE 'ZCA_ADD_TO_CART_%'
    OR configuration_key LIKE 'ZCA_CHECKOUT_%'
    OR configuration_key LIKE 'ZCA_CAROUSEL_%'
    OR configuration_key LIKE 'ZCA_PRIMARY_ADDRESS_%';
```

**Comment by lat9** [comment]
1. Why should the "Body Rating Stars Background Color" be set to `#000000` by default?  That looks pretty ugly: 
![image](https://user-images.githubusercontent.com/2685585/220708942-755f97ac-2668-4dd9-a549-da8e64443f90.png)

2. The default coloring for the **Header EZ-Page Bar** group: 
![image](https://user-images.githubusercontent.com/2685585/220706509-cecd9677-a9c2-46cb-a374-d0fc395ed223.png)
is the same as that for the **Footer EZ-Page Bar** group: 
![image](https://user-images.githubusercontent.com/2685585/220706781-d347836e-91eb-48ab-92fc-2f17ea4a3a97.png)
and, if the colors are not `not-set`, the respective hover-colors are also included in the CSS rendering.

I'll check on the cat-tabs' active link stuff next.

**Comment by lat9** [comment]
For those active-link-on-hover settings, without the hover additions, hovering on the active item 
![image](https://user-images.githubusercontent.com/2685585/220709940-a90444a8-94dc-4694-b02d-18988600817c.png)
looks the same as hovering on an inactive item.

With the hover additions, it's obvious that you're hovering on the active item
![image](https://user-images.githubusercontent.com/2685585/220710330-a9127d74-6400-47e3-b55a-ef3ad49001b0.png)

**Comment by lat9** [comment]
Noting that the change to using `#ad3000` was not reflected in your original PR (#208).  Should *all* `#ad0000` colorings be changed to that as well?

**Comment by lat9** [comment]
> Noting that the change to using `#ad3000` was not reflected in your original PR (#208). Should _all_ `#ad0000` colorings be changed to that as well?

@dbltoe, I'm "fixin' to" do the v3.5.2 release, just waiting on this.  I'll be releasing this afternoon with or without an answer.

**Comment by dbltoe** [comment]
Sorry, just back to the computer yesterday.  The reds should be #ad0000 as some of them are smaller font than others.  If all were large fonts, the other would work.  Smaller requires 7.5:1 versus 4.5:1 for large.

A pr for h tags and aria labels follows
