### ISSUE TITLE
init_bc_config_install_or_upgrade.php issues

### ISSUE THREAD

**Issue by dennisns7d** [lat9/ZCA-Bootstrap-Template#218]
Some of the issues I've encountered are very minor while others are a bit more serious.

Color specification uses upper case. IMO they should be lower case to be consistent with the majority.

- '#0099CC' in lines 199 & 209
- '#007E33' in lines 543 & 567

The configuration_title for `ZCA_HEADER_TABS_ACTIVE_COLOR_HOVER` should have ' on Hover' appended to it in line 332.

The configuration_value for `ZCA_PRIMARY_ADDRESS_ADDRESS_BACKGROUND_COLOR` fails the contrast check. The current value is the value used in bootstrap.css. IMO it should probably follow the color change used elsewhere when transitioning from "success" colors, so the value should be '#00813' in line 697.

Similarly the configuration_values for `ZCA_PRIMARY_ADDRESS_CARD_HEADER_BACKGROUND_COLOR` and `ZCA_PRIMARY_ADDRESS_CARD_BORDER_COLOR` should follow the color change used elsewhere when transition from "primary" colors, so the values should be '#007faf' in lines 711 and 725.

**Comment by lat9** [comment]
> The configuration_value for `ZCA_PRIMARY_ADDRESS_ADDRESS_BACKGROUND_COLOR` fails the contrast check. The current value is the value used in bootstrap.css. IMO it should probably follow the color change used elsewhere when transitioning from "success" colors, so the value should be '#00813' in line 697.
> 

Almost done, with the exception of this one; I'm presuming that the color value should be '#008a13', right?

**Comment by lat9** [comment]
@dennisns7d, please review.

**Comment by dennisns7d** [comment]
Looks good. And yes, the color value should be '#008a13'.

**Comment by lat9** [comment]
Thanks (again).  Since this issue is associated with the beta's processing, I'm closing it at this time.
