### ISSUE TITLE
default should be other way...

### ISSUE THREAD

**Issue by proseLA** [lat9/ZCA-Bootstrap-Template#230]
https://github.com/lat9/ZCA-Bootstrap-Template/blob/e3d38003b7fdf4c117f51d6a7348e140138635d4/includes/modules/bootstrap/attributes.php#L123-L125

i think the default here should be 1.  probably an edge case...

i acknowledge i am running 3.3.0 (and in need of an update).  but in this version, when 0, the comment on the attribute appears OUTSIDE of the `<div>` associated with that attribute.  that just seems wrong to me.

and for those of us (okay probably only me) that want to manipulate the DOM after the fact, it makes life a little harder....

it seems that the field was added in some version after the one i am using 1.5.7; although the update for that table way back when may have failed.  i have not looked.

**Comment by lat9** [comment]
The field (`products_options::products_options_comment_position`), added in zc158, has a database default of 0.

**Comment by proseLA** [comment]
> The field (`products_options::products_options_comment_position`), added in zc158, has a database default of 0.

a new field in 158 with a default of 0.  not really sure how that affects this issue.  nor do i have any idea why that field was added.  

the position element has been there since the initial github commit.  swguy added [the field here into the db.](https://github.com/zencart/zencart/commit/cdfcff863ce64b0ed2c754590cfb6ab9d301258b)  why the field is now needed, i have no idea.  what the field does, i'm not quite sure.  why it is a smallint(2), when the only acceptable values are `1` or `0`, again i have no idea.

all i know is that in this template, when the value is 0, the comment exists outside of the div for the attribute element.  and i think that is wrong.  example of it set to 0:

```
<div id="attributes-card" class="card mb-3">
    <h4 id="attributes-card-header" class="card-header">Please Choose: </h4>
    <div id="attributes-card-body" class="card-body p-3">

        <h5>Serial number of product</h5>

        <!--bof attribute options card-->
        <div id="attributeOptionstxt-attrib-110-card" class="card mb-3">
            <h4 id="attributeOptionstxt-attrib-110-card-header" class="card-header optionName"><label class="attribsInput" for="attrib-110-0">Serial Number</label></h4>
            <div id="attributeOptionstxt-attrib-110-card-body" class="card-body p-3">
                <input class="form-control" type="text" name="id[txt_110]" size="32" maxlength="32" value="" id="attrib-110-0" data-key="attrib-110-0" >
...
```

now when it is set to 1, the comment exists within the div of `attributeOptionstxt-attrib-110-card`, which makes sense to me:
```
<div id="attributes-card" class="card mb-3">
    <h4 id="attributes-card-header" class="card-header">Please Choose: </h4>
    <div id="attributes-card-body" class="card-body p-3">
        <!--bof attribute options card-->
        <div id="attributeOptionstxt-attrib-110-card" class="card mb-3">
            <h4 id="attributeOptionstxt-attrib-110-card-header" class="card-header optionName"><label class="attribsInput" for="attrib-110-0">Serial Number</label></h4>
            <div id="attributeOptionstxt-attrib-110-card-body" class="card-body p-3">
                <input class="form-control" type="text" name="id[txt_110]" size="32" maxlength="32" value="" id="attrib-110-0" data-key="attrib-110-0" >

                <div>Serial number of product</div>
...
```

so the issue is not really about the field; the issue is why that would exist outside of the div for that element.

i suppose at the end of the day, i just think css is awesome, and this is just another one of those examples.
