### ISSUE TITLE
product listing row: model title center-aligned, model data left aligned

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#233]
![image](https://user-images.githubusercontent.com/4391026/231109422-09344c10-0f71-40b2-897e-f0d59c00f76d.png)

Title
https://github.com/lat9/ZCA-Bootstrap-Template/blob/0e6169eb03c83910c044596974786f397d2f33d7/includes/modules/bootstrap/product_listing.php#L52-L56

Data
https://github.com/lat9/ZCA-Bootstrap-Template/blob/0e6169eb03c83910c044596974786f397d2f33d7/includes/modules/bootstrap/product_listing.php#L291-L297

ZC Core
Title
```
            case 'PRODUCT_LIST_MODEL':
                $lc_text = TABLE_HEADING_MODEL;
                $lc_align = '';
                $zc_col_count_description++;
                break;
```

Data
```
                case 'PRODUCT_LIST_MODEL':
                    $lc_align = 'center';
                    if ($product_listing_layout_style === 'table') $lc_align = '';
                    $lc_text = '';
                    //if ($product_listing_layout_style === 'columns') $lc_text .= '<label>' . TABLE_HEADING_MODEL . '</label>';
                    $lc_text .= $listing_model;
                    break;
```

I'm not sure of the significance of 'table' style in this context, why it influences the alignment and why the title and data should be different/not under the same clause.

**Comment by lat9** [comment]
> I'm not sure of the significance of 'table' style in this context, why it influences the alignment and why the title and data should be different/not under the same clause.

The alignment, albeit wonky, of the model's data follows the ZC Core _at this time_ &mdash; although the heading centering is different.  Having looked at the table vs. row rendering, I believe that both the heading and the data should be center-aligned _regardless_ the table vs. row layout selected.
