### ISSUE TITLE
NavBar buttons (other than AJAX search icon) need their own coloring

### ISSUE THREAD

**Issue by dennisns7d** [lat9/ZCA-Bootstrap-Template#247]
Issue #246 prompted me to do some investigating into the navbar button coloring.

I found that the `ZCA_HEADER_NAVBAR_BUTTON_*` colors were applied only to `nav.navbar .navbar-toggler` and `nav.navbar .navbar-toggler:hover` (the hamburger menu button). The non-AJAX header search form's submit button is currently colored by the `ZCA_BUTTON_*` colors, but could be colored by the `ZCA_HEADER_NAVBAR_BUTTON_*` colors by adding the following in the appropriate places in includes/templates/bootstrap/css/stylesheet_zca_colors.php:

`nav.navbar .btn,` before `nav.navbar .navbar-toggler`
`nav.navbar .btn:hover,` before `nav.navbar .navbar-toggler:hover`

**Comment by dennisns7d** [comment]
It's more of a wording issue. The ZCA Bootstrap Colors admin page refers to "Header Nav Bar Button", yet the values don't apply to any button in the nav bar except the hamburger menu button.

**Comment by lat9** [comment]
So, perhaps just changing the wording associated with that color-setting to make it more obvious?

**Comment by dennisns7d** [comment]
That would be less confusing/misleading, though I personally prefer to be able to set the navbar buttons values different that the other buttons. Not a show-stopper issue.

**Comment by lat9** [comment]
Point taken.  I'll take a quick peek at those button defaults .... seems like at least a non-background border-color would suffice to enable the coloring to apply to _all_ buttons in the header.

**Comment by dbltoe** [comment]
also missing are all the combinations for .alert-info.  It is rarely seen but, if we are going to allow the ease of color change....

.alert-info {color: #13525e, background-color: #d1ecf1, border-color: #bee5eb

based on defaults.

Should I add that when fixing the spaces?

**Comment by lat9** [comment]
Let's keep the changes separate.  If you do the 'heavy lifting' on the current coloring-changes, I'll get this one.

**Comment by lat9** [comment]
> also missing are all the combinations for .alert-info. It is rarely seen but, if we are going to allow the ease of color change....
> 
> .alert-info {color: #13525e, background-color: #d1ecf1, border-color: #bee5eb
> 
> based on defaults.
> 
> Should I add that when fixing the spaces?

Noting that those were/are included in the updates for #353.
