### ISSUE TITLE
modalboxes, tpl_image_additional no image src

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#259]
No alt or src?
https://github.com/lat9/ZCA-Bootstrap-Template/blob/1a92c4d8b7ec0fa39218615ba9e8024c86ed4790/includes/templates/bootstrap/modalboxes/tpl_image_additional.php#L24

Consequently giving me a validation error.

**Comment by lat9** [comment]
Noting that the `src=` gets filled in by the template's jQuery processing on-click.  I'll add the 'no-picture' image and an `alt=` containing "Additional image for $product_name" to make the validator 'happy'.

**Comment by torvista** [comment]
I'm still very much in the dark with this template....

**Comment by lat9** [comment]
> I'm still very much in the dark with this template....

It's got a lot going on, between the bootstrap classes and the underpinning provided by the template's observer to add required bootstrap classes to various form elements to get them to render properly and consistently.
