### ISSUE TITLE
Question: misspelling

### ISSUE THREAD

**Issue by drbyte** [lat9/ZCA-Bootstrap-Template#26]
Should we adjust all the constants that have misspellings in them? 
eg: `ZCA_BUTTON_PAGEINATION_COLOR` and its variants

**Comment by lat9** [comment]
That's going to cause issues for sites that are upgrading ... unless there's an initialization file also supplied that checks to see, for each of the renamed constants
```
if (!defined('NEW_CONSTANT_NAME') && defined('OLD_CONSTANT_NAME')) define('NEW_CONSTANT_NAME', OLD_CONSTANT_NAME);
```

**Comment by drbyte** [comment]
> That's going to cause issues for sites that are upgrading

Agreed. Hence posting the question instead of writing code first. :)

**Comment by lat9** [comment]
Let's just leave them as they are.
