### ISSUE TITLE
Sold Out Button:  Add coloring and remove hover pointer (it's not clickable!)

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#261]
Add background/color/border colors (no hover because it's not clickable) for the "Sold Out" button and update the CSS to use the 'appropriate' pointer.

**Comment by dbltoe** [comment]
Is there no scenario where the store owner might want to have the text change on hover?
https://tinyurl.com/2k6oka2o

**Comment by lat9** [comment]
That's an _extreme_ corner-case.

**Comment by dbltoe** [comment]
The only scenario I could think of was one of our customers that has several fast-moving items.  Certain parts of the year, they can't keep enough in house and often have items go out of stock between closing and opening.  It might work for them to have the button go to Restocking.
Still, as you say, that's extreme.
