### ISSUE TITLE
Rating Star's Default color/background-color Changes

### ISSUE THREAD

**Issue by dbltoe** [lat9/ZCA-Bootstrap-Template#274]
Came across a new (to me) contrast checker at https://github.com/ThePacielloGroup/CCAe.  One advantage of this checker is that you can "lock in" shades and, using the left and right arrows, change r, g, and b at the same time.

I was playing with its extra features and decided to give the rating star thing a try with the original background of #ffffff as I've never been fond of the workaround we had to do.

The result was #987000 which looks like a viable alternative.  It's especially better than having the #322424 background with #efa31d and it meets the color contrast ratio for that item in all the testers I have at my disposal.

Take a look at the result on haredoDOTcom and see what you think.  If you like it, throw it in whenever you feel appropriate.

I didn't want to muddy up the important stuff with a PR for this.

**Comment by lat9** [comment]
`#987000` is, IMO, as ugly as the current `#322424`:
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/2685585/4a8583e6-300f-4b95-ada4-53055716fb5d)

What's so wrong with a white background?
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/2685585/f31a6a36-728b-4bf3-9455-e922653a2f80)

**Comment by lat9** [comment]
What about changing the background to `#ffffff` and the color to `#987000`?  Does that make the contrast better:
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/2685585/9226ce7f-f326-43fa-a460-0c3aa494af01)

**Comment by dbltoe** [comment]
Using #987000 with #ffffff as the background is the absolute minimum contrast that still looks like gold and exceeds minimums at 4.51:1 in contrast, which is what I intended with the original post.
The current default of #efs31d results in a contrast ratio of 2.12:1.  Total failure.
