### ISSUE TITLE
Cart + Shipping Estimator Layout

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#279]
![2023-08-20 14_21_53-The Shopping Cart _ Zen Cart!, The Art of E-commerce — Mozilla Firefox](https://github.com/lat9/ZCA-Bootstrap-Template/assets/4391026/2c1b72ea-267f-4c64-bbf4-915a603a59eb)

width:100% is used everywhere.

Perhaps at least dropdowns should fit their content instead of their container.
The input fields look bad/should have a sensible size.
The rates table could also fit content.

**Comment by torvista** [comment]
This is with
#shippingEstimatorContent {
  width: fit-content;
}

![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/4391026/ba2363c9-3479-4e7f-98a7-ab25b7475b6d)

**Comment by lat9** [comment]
I've neglected testing that display-on-page version as I usually use the modal display.
