### ISSUE TITLE
Bootstrap search + observer causes debug when no results

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#294]
This falls between two camps, but is really a general question on SQL.
I'm getting a debug when there are no results. The debug only occurs as the query gets modified by an observer.
PHP Warning: Undefined array key "count" in includes/classes/ajax/zcAjaxBootstrapSearch.php on line 53.
line 53: $search_results_count = (int)$count->fields['count'];

SQL without observer (no debug):
$count->fields['count'] = 0.

> SELECT COUNT(*) AS count   FROM products p
>                             INNER JOIN products_description pd
>                                 ON pd.products_id = p.products_id
>                                AND pd.language_id = 1 WHERE p.products_status = 1  AND ( (  pd.products_name LIKE '%evox%' OR  p.products_model LIKE '%evox%')  )

SQL with observer (debug):
$count->fields['count'] is not set.

>  SELECT COUNT(*) AS count   FROM products p
>                             INNER JOIN products_description pd
>                                 ON pd.products_id = p.products_id
>                                AND pd.language_id = 1 LEFT JOIN products_options_stock posm ON (posm.products_id = p.products_id) WHERE p.products_status = 1  AND ( (  pd.products_name LIKE '%evox%' OR  p.products_model LIKE '%evox%')  ) OR posm.pos_model LIKE '%evox%' GROUP BY
>              p.products_image, p.products_id, p.products_sort_order, pd.products_name, p.master_categories_id, p.products_model, posm.pos_model

If I use SELECT COUNT(p.products_id) it is the same (not set).

Any clues?

**Comment by lat9** [comment]
Very strange, I've never seen `COUNT(*)` return no results.  I guess the correction for line 53 would be
```php
$search_results_count = (int)($count->fields['count'] ?? 0);
```

**Comment by torvista** [comment]
That's what I did as a sticking plaster.

**Comment by dbltoe** [comment]
like the problem with no categories, if COUNT(*) is looking at an empty table, there will be no result.
WHERE clauses that eliminate rows in a table and bad JOINs also can cause this.
Also, of course, query errors.

**Comment by torvista** [comment]
It was the GROUP BY from the observer.
I got rid of all that, the count was 0 and the query/search still worked with POSM.

**Comment by lat9** [comment]
Interesting, open an issue on the POSM repo so that I remember and can review.
