### ISSUE TITLE
ZCA Bootstrap Colors: UI improvements and default now included in exported .csv

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#296]
I had a lot of items not-set in the admin table.

So I modified the export to include an extra column containing the default value, then imported that as the value column to reset all to default.
Possibly that is a process others would wish to do? Or I am missing something?

Also I modified the value column to only show a value if it was modified from default, and monospaced the colour codes, which made it easier on the eye.

**Comment by torvista** [comment]
or you could just import all the Values as empty to use the default values... :confounded:

**Comment by dbltoe** [comment]
Can we see, please?

**Comment by torvista** [comment]
eg:
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/4391026/d4af8e60-26b8-4c22-a776-8b95dc906b30)

to

![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/4391026/328d1c1d-9f05-467d-b0b8-9cac00e3492b)

**Comment by lat9** [comment]
@torvista, if you supply those changes (either here or to my direct email) I'll get those changes incorporated into v3.6.2.

**Comment by lat9** [comment]
Updates provided based on the changes that @torvista provided.
