### ISSUE TITLE
Rating stars background color is "ugly"

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#301]
What the heck is up with that black background?
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/2685585/c1b44bbe-49a3-4a64-8cfc-bad991023891)

IMO, `#ffffff` (white) is a **_much better_** default:
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/2685585/3fed83b8-9592-41e1-a4bc-6f546ba1d48f)

**Comment by dennisns7d** [comment]
Noting that issue #274 is related.
