### ISSUE TITLE
template_info.php is out of date

### ISSUE THREAD

**Issue by dennisns7d** [lat9/ZCA-Bootstrap-Template#302]
The includes/templates/bootstrap/template_info.php file has not had `$template_version` updated since version 3.6.0.

**Comment by lat9** [comment]
Sigh, one more thing to put on the files-to-upgrade-when-updating list.  Thanks for the report.

**Comment by lat9** [comment]
> Sigh, one more thing to put on the files-to-upgrade-when-updating list. Thanks for the report.

Actually, since that file's expected to run solely in the admin, just use the template's current version as defined in the template's admin initialization file.
