### ISSUE TITLE
Two trash cans per product on shopping cart page

### ISSUE THREAD

**Issue by daphilli224** [lat9/ZCA-Bootstrap-Template#304]
On the shopping cart page, two trash cans are displayed per product on small devices. One is displayed under the product quantity and the other in the extreme right column. Screen shot attached. I'm not sure what the design intent is but if the intent is to display only one can on all device sizes, one fix is to change the div class from "d-md-none mt-1" to "d-sm-none mt-1" on line 87 of bootstrap/templates/tpl_shopping_cart_default.php.
zc158a, ZCA-Bootstrap-Template 3.6.1 (and 3.6.2). 
<img width="664" alt="Screenshot 2024-01-15 at 9 00 13 AM" src="https://github.com/lat9/ZCA-Bootstrap-Template/assets/91150056/82b9fe33-a682-4d46-a01e-77cd2b5f5ff7">

**Comment by lat9** [comment]
What device-width is displaying in that manner?

**Comment by daphilli224** [comment]
Hi Cindy,

From approximately 561 through 752px. My iPhone in landscape mode. On a desktop, just resize the window smaller and smaller and you’ll see it.

Dave

PS: Thanks for all the work you put in to make this template. I find it so much easier than the classic responsive template.

**Comment by daphilli224** [comment]
The problem is that line 87 and 135 in the cited file both trigger trash can display for "sm" devices.
Hope this helps.
Dave
