### ISSUE TITLE
Suggestion: dynamic determination of categories per row 

### ISSUE THREAD

**Issue by scottcwilson** [lat9/ZCA-Bootstrap-Template#305]
The file `includes/modules/bootstrap/product_listing.php` determines the number of products per row when Admin > Configuration > Product Listing > Columns per row = 0.  This is very powerful especially coupled with an overridable `$grid_classes_matrix` variable.  

It would be great to have similar capabilities for the display of number of categories per row in `includes/modules/bootstrap/category_row.php` versus using the static number set with Admin > Max values > Categories per Row.

**Comment by drbyte** [comment]
That would be the `$product_listing_layout_style = 'fluid'` logic.

**Comment by drbyte** [comment]
See https://github.com/zencart/zencart/pull/6192

**Comment by drbyte** [comment]
[fluid-cat-list-bs4-template.zip](https://github.com/lat9/ZCA-Bootstrap-Template/files/14154722/fluid-cat-list-bs4-template.zip)

This is a zip of the changed files from BS4 template v3.6.2, which make this work.
Pretty sure it's backwards compatible to v158.

**Comment by lat9** [comment]
@drbyte, close but I don't like the gutter-less display ... working on it!

![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/2685585/94efd5ce-bf54-48b7-9345-8ff5ea2aaee7)

**Comment by lat9** [comment]
Never mind, I missed those additional parameters for the fluid display!

**Comment by lat9** [comment]
See also [this](https://github.com/lat9/ZCA-Bootstrap-Template/wiki/Frequently-Asked-Questions#configuration--maximum-values--categories-to-list-per-row-display-anomalies) Wiki article regarding usage.

**Comment by scottcwilson** [comment]
Thanks!  Adding this link to the help.
