### ISSUE TITLE
PHP Warnings generated by tpl_modules_listing_display_order.php if no matching products are found

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#307]
... since the `$display_order` variable isn't set.

**Comment by lat9** [comment]
Noting that this was corrected via [this](https://github.com/zencart/zencart/commit/42791f572cc0e4d8168596a6c9b7ce448a554db5) Zen Cart base commit.

**Comment by drbyte** [comment]
FYI: the `--RESET--` option was removed, 
in favor of adding `'TEXT_INFO_SORT_BY_RECOMMENDED' => 'Recommended',`
in https://github.com/zencart/zencart/pull/6186/files#diff-3a08b972bb3a9eab73668ae74aa4d6b935839e983f312a7396ae77ae1994a195

**Comment by lat9** [comment]
Thanks for the heads-up!
