### ISSUE TITLE
Don't display the back-to-top icon on small/medium screens

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#316]
I guess my _assumption_ is that those screen-sizes are associated with mobile/tablet devices which have screen-swipe capability.

**Comment by barco57** [comment]
Yeah, should only exist on desktop. I looked at walmart.com, amazon.com, pinterest.com (which you can scroll endlessly), and wayfair.com, on my phone and none of them has a back-to-top.
