### ISSUE TITLE
Suggested: style links with underline

### ISSUE THREAD

**Issue by scottcwilson** [lat9/ZCA-Bootstrap-Template#324]
Making this change takes a default installation from a Lighthouse score of 92 to 96.  

Update `includes/templates/bootstrap/css/stylesheet.css` with 

```
a {
   text-decoration: underline;
}
```

**Comment by lat9** [comment]
Sounds good, but that change will be created in `stylesheet_364.css` as a browser cache-busting update.  Otherwise, any browser cache of `stylesheet.css` won't have the change.

**Comment by lat9** [comment]
For whatever reason, the changes I just pushed for this issue didn't 'attach'.
