### ISSUE TITLE
Categories-row:  `id=` parameter "lost" when viewing in fluid mode

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#330]
When `Configuration :: Maximum Values :: Categories to List Per Row` (MAX_DISPLAY_CATEGORIES_PER_ROW) is set to a non-zero value, that identifies the fixed number of categories to display per row.  With this setting, the wrapping `<div>` includes an `id=subCategory-card-body` attribute.

When configured as `0` (fluid layout), that `id=` attribute is not included.

**Comment by lat9** [comment]
Root cause: `includes/templates/bootstrap/common/tpl_columnar_display.php` is used and has no provision for adding either the `id=` attribute or an additional class to that card-body wrapping div.

**Comment by drbyte** [comment]
> Root cause: `includes/templates/bootstrap/common/tpl_columnar_display.php` is used and has no provision for adding either the `id=` attribute or an additional class to that card-body wrapping div.

There's probably value in adding support for that in the core ZC template.

**Comment by drbyte** [comment]
How about this in `tpl_columnar_display.php`:
```diff
-<div class="card-body text-center">
+<div class="card-body text-center"<?= (!empty($card_body_id) ? ' id="$card_body_id"' : '') ?>>
```
and then in `tpl_modules_category_row.php` define the var up top, say line 17-ish:
`$card_body_id='subCategory-card-body';`

**Comment by lat9** [comment]
That's what I'm thinking, but also looking at the other centerboxes (e.g. featured) that have 'chosen' to provide their rendering without use of `tpl_columnar_display.php`.
