### ISSUE TITLE
html_header update

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#337]
I'll note there are a lot of differences between BS and ZC version of this file at the moment, making merging/comparing more onerous than necessary. 
I'd suggest the ZC file gets a spring clean before release to make things easier.

**Comment by lat9** [comment]
Yep, since the Bootstrap template is its own entity, I've got more "freedom" to do those reformatting/refactoring exercises.  Noting that this issue should be raised on the Zen Cart GitHub, because I'm not planning on taking the template backwards.

**Comment by torvista** [comment]
Since I don't think anything actually needs fixing, I don't think it is **normally** justified to rework a core file for no concrete reason.

But since core files are the starting point, and changes need propagating to user templates, having a plugin file with many sections "more-advanced" (cosmetically) than a core file is cart before the horse and leads to people making decision...is this important or not etc.

Maybe there should be more flexibility/consideration/encouragement allowed for this situation: if someone is working on a plugin that enhances core, cosmetic changes to core should be allowed to facilitate that, to provide an "updated" base.

Which is a corollary of my point of view that any contribution to the core however minor should be allowed/encouraged as that can only lead to more and better input.
