### ISSUE TITLE
BOX_SHOPPING_CART_DIVIDER is no longer defined.

### ISSUE THREAD

**Issue by proseLA** [lat9/ZCA-Bootstrap-Template#341]
https://github.com/lat9/ZCA-Bootstrap-Template/blob/bc632e533527d465919a0469c2e24be27a0b5321/includes/templates/bootstrap/sideboxes/tpl_shopping_cart.php#L21

see [this commit.](https://github.com/zencart/zencart/commit/775c584f9676feecd329b8b54444597d8c5b7ffc)

finding the removal in the language file would prove impossible.

**Comment by lat9** [comment]
Sweet; thanks for the heads-up.

**Comment by lat9** [comment]
... but the comments above that line tell the full story.  Once the template drops support for Zen Cart versions prior to 1.5.8, that section can be changed to fully drop the fall-back use of `BOX_SHOPPING_CART_DIVIDER`.

https://github.com/lat9/ZCA-Bootstrap-Template/blob/bc632e533527d465919a0469c2e24be27a0b5321/includes/templates/bootstrap/sideboxes/tpl_shopping_cart.php#L17-L21
