### ISSUE TITLE
line-height settings for h tags

### ISSUE THREAD

**Issue by dbltoe** [lat9/ZCA-Bootstrap-Template#348]
I just loaded a test site of ZC 2.0 with the latest OPC, EO, and Bootstrap.

I haven't determined which one of the stylesheets is setting the line-height for h tags to 1.2 overriting with $line-height-base.  Thus changing the 1.5 set in the body tag to 1.2.  WCAG recommends 1.5 times basic font size for line height which is why 1.2 is triggering the the SiteImprove Accessibility Checker for a AAA error.  axe Dev Tools does not show it but it is not always accurate on AAA requirements.

**Comment by lat9** [comment]
You don't say what version of Bootstrap.  I'm running v3.6.4 on zc200-rc2 and don't see such an override.  Perhaps you could identify a page to check.

**Comment by dbltoe** [comment]
Running the same with a clone of basic 3.6.4.

And, dropping to non-cloned 3.6.4 cleared the problem.  Apparently a bad clone.
