### ISSUE TITLE
Correct product-listing/category-row display for 'columns' display

### ISSUE THREAD

**Issue by proseLA** [lat9/ZCA-Bootstrap-Template#359]
i'm not really sure how people use this template out of the box.  maybe i am missing something.

i think i am using this with all of the default settings.  

my layout style based on that is now `columns`.

based on that, i now have a percentage for column width as dictated by this code:

https://github.com/lat9/ZCA-Bootstrap-Template/blob/369f28873e647fc80a55f58bd216ea0f39a632e6/includes/modules/bootstrap/product_listing.php#L122-L130

given the fact that there are only 3 products in this category, i now have a column width of 32.5; which looks to be a percentage as dictated here:

https://github.com/lat9/ZCA-Bootstrap-Template/blob/369f28873e647fc80a55f58bd216ea0f39a632e6/includes/modules/bootstrap/product_listing.php#L392-L394

and now, we use that with in-line styling (noooooo!!!!!!) here:

https://github.com/lat9/ZCA-Bootstrap-Template/blob/369f28873e647fc80a55f58bd216ea0f39a632e6/includes/modules/bootstrap/product_listing.php#L395-L396

and then it finally gets output here:

https://github.com/lat9/ZCA-Bootstrap-Template/blob/369f28873e647fc80a55f58bd216ea0f39a632e6/includes/templates/bootstrap/common/tpl_columnar_display.php#L30-L43

which is already a div within a div within a div.  which is fine.  except the product display is now _32.5% of the **column**_ as opposed to 32.5% of the viewporrt.

see: 

![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/1095136/9c1a07ec-c21d-4e5e-adbf-fa21800f1505)

what might i be missing?

removing the `$style` on line 396 above seems to resolve the issue.  see:

![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/1095136/c491bc2c-0780-4e13-844f-26464195c818)

again, what might i be missing here?

**Comment by lat9** [comment]
This configuration setting's directions:
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/2685585/16941601-fec3-4549-a1f2-e0c8f676ea2a)

Combined with [this](https://github.com/lat9/ZCA-Bootstrap-Template/wiki/Frequently-Asked-Questions#configuration--product-listing--columns-per-row-display-anomalies) Wiki article.

**Comment by proseLA** [comment]
this does not explain the problem that i have presented.

you are explicitly stating that you do not recommend using a number other than 0 or 1.  but if one chooses to use a non recommended number, the calculation is completely wrong.  is that why it is not recommended?

0 or 1 is either fluid or row.  so you do not recommend column.  the only time this style error occurs is in a non recommended setting, ie column.  

so again, given that we are now in a non-recommended setting (which i can only mean non-supported) why is that in-line style width there?  it makes no sense to me.  and i think it should be removed.

unless you can present a situation where that in-line style would be correct.  which i would be more than willing/anxious to hear.

**Comment by lat9** [comment]
Thanks for sussing that out; same issue applies to the `category_row.php` module.
