### ISSUE TITLE
Enable a site to "not display" categories with no products

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#360]
... as submitted via PR #357.

**Comment by lat9** [comment]
Noting that the referenced PR deals with the "Categories Tabs" only; I'll be updating the categories' sidebox to also adhere to this setting.

**Comment by torvista** [comment]
While you're fiddling with this, I would comment that I've just modified it to allow the manual specifying of categories to skip.
Maybe that's an edge case or something worth including for these queries?

**Comment by lat9** [comment]
> While you're fiddling with this, I would comment that I've just modified it to allow the manual specifying of categories to skip. Maybe that's an edge case or something worth including for these queries?
That's a site-specific edge-case, which is why templates can be overridden!

**Comment by lat9** [comment]
For downward-compatibility, I'll be switching the default from "don't display" to "display".
