### ISSUE TITLE
tpl_search_header.php mid-content terminated with a semicolon

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#368]
https://github.com/lat9/ZCA-Bootstrap-Template/blob/e9e92711fae7969c56219bbbcb435cbf2237d689/includes/templates/bootstrap/sideboxes/tpl_search_header.php#L19

I think this semicolon should be a .

**Comment by lat9** [comment]
You were correct; thanks for watching my back.
