### ISSUE TITLE
html_header preloading duplicated?

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#374]
Maybe I'm missing something but it seems the preloading is repeated:

All
https://github.com/lat9/ZCA-Bootstrap-Template/blob/753281d52b14f3a31833ec5aaa6a436d8377f3d7/includes/templates/bootstrap/common/html_header.php#L77-L78

CSS
https://github.com/lat9/ZCA-Bootstrap-Template/blob/753281d52b14f3a31833ec5aaa6a436d8377f3d7/includes/templates/bootstrap/common/html_header.php#L116-L117

Jscript
https://github.com/lat9/ZCA-Bootstrap-Template/blob/753281d52b14f3a31833ec5aaa6a436d8377f3d7/includes/templates/bootstrap/common/html_header.php#L194-L195

and so $zca_no_preloading = true only prevents the first loop/duplication.

**Comment by lat9** [comment]
Correct, setting `$zca_no_preloading` simply disables the (er) preloading of the various style/script links.  The follow-on loops actually bring in the styles and script.

**Comment by torvista** [comment]
Doh!
