### ISSUE TITLE
PHP Warning: Undefined variable $script_name in jscript_bs4_matching_heights.php

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#381]
php 8.3.7RC1, strict reporting

> 
> [09-May-2024 16:11:57:000000 Europe/Madrid] Request URI: /
> IP address: 127.0.0.1, Language id 2
> #0 includes/templates/bootstrap/jscript/jscript_bs4_matching_heights.php(10): zen_debug_error_handler()
> #1 includes/templates/bootstrap/common/html_header.php(226): require('D://OneDrive//Bus...')
> #2 index.php(42): require('D://OneDrive//Bus...')
> --> PHP Warning: Undefined variable $script_name in includes/templates/bootstrap/jscript/jscript_bs4_matching_heights.php on line 10.

If the ajax search is on, $script_name is set here I think:

https://github.com/lat9/ZCA-Bootstrap-Template/blob/08b92995cb0c7c3bafc02d8b13975d5dc0786c74/includes/templates/bootstrap/jscript/jscript_bs4_ajax_search.php#L5-L11

and conversely, if off, is not set.

**Comment by torvista** [comment]
What took you?

**Comment by lat9** [comment]
> What took you?

??

**Comment by dbltoe** [comment]
I believe he's referring in your taking a WHOLE 19 minutes to "get 'er done".  😃
