### ISSUE TITLE
Down for maintenance for others messages flashes then disappears 

### ISSUE THREAD

**Issue by scottcwilson** [lat9/ZCA-Bootstrap-Template#385]
The message 

    'TEXT_ADMIN_DOWN_FOR_MAINTENANCE' => 'NOTICE: The website is currently down for maintenance to the public',

is not displayed as expected. 

Repro steps: for a site on the public Internet, be sure your IP is in the Down For Maintenance (exclude this IP-Address) list, then put the site down for maintenance.  Open the storefront, and observe that the message does not stay up.

**Comment by dbltoe** [comment]
Taking a quick inspect, it looks like the simplest fix is to move it after the headerWrapper and in front of the navMainWrapper.

**Comment by lat9** [comment]
The fixed-navbar was 'getting in the way'.  I'll be moving those 'header' messages below the logo section in the header, keeping the navbar+logo together:
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/2685585/90a2b973-b03f-4e61-ae19-f71a741a33bb)
