### ISSUE TITLE
Additional Images Carousel: image 0 bad title and size

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#393]
zencart master with Bootstrap and Image Handler dropped in.
Image Handler disabled (but I note that on my site when enabled, image 0 is not coming from bmz_cache as per the other additional images).

image 0 size is different to the rest and the title is incorrect.

![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/4391026/6d4a73df-95a3-4f91-8b10-4c10e9b7a160)

**Comment by lat9** [comment]
"Interesting", since what I'm seeing (no IH installation) is
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/2685585/9c7becff-c4c8-4117-8812-84f1cb8bf5fa)

**Comment by torvista** [comment]
Dev tools is showing the displayed **main** image: hover over the thumbnail, that's the oddity.
