### ISSUE TITLE
shipping estimator: simple syntax??

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#394]
https://github.com/lat9/ZCA-Bootstrap-Template/blob/b11499fe7bee2d58cd9244a63031a4401092c7ae/includes/templates/bootstrap/templates/tpl_modules_shipping_estimator.php#L85

I'm not understanding this construct:

` ${'postcode'}`

which is not in current ZC.

And this is so different to the core version, it's quite a comparison headache.

**Comment by lat9** [comment]
> Would it help if I updated this to match the core file as much as possible?

No.
