### ISSUE TITLE
AJAX search doesn't search in a product's description

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#409]

**Comment by proseLA** [comment]
for every person that wants to include search in description, there is another one that does not to include search in description.  if we want to mimic what the base ZC does, i believe that offers a selection as to whether we want to search in a description or not.

in addition, adding (or subtracting) any field into the method `zen_build_keyword_where_clause` is very easily done using [the notifier.](https://github.com/zencart/zencart/blob/1ae814ce0a492d908735a1f8ca9d407220636064/includes/functions/functions_search.php#L164)

what does all of this mean?  i'm just not sure this is a bug v intended behavior.  searching in an ajax search and adding the description could really bog down the user experience as the ajax search gets executed for every keystroke (at least i think it does).  

in any event, i think this should be configurable if you want to address this change.

**Comment by lat9** [comment]
That's how the 'base' Zen Cart sidebox search works ... I thought (although I haven't used that for eons).

I'll revisit; sounds like it might be yet-another Bootstrap configuration setting.

**Comment by proseLA** [comment]
oh... interesting...  good point.  i was not thinking about the sidebox...  i was thinking about the search results page...

even given that, i'm still of the opinion it should be configurable for the reason i mentioned above.

**Comment by lat9** [comment]
I'm probably going to be _naughty_ with this one, since I'm not a big fan of soft-configuration settings, and introduce that additional configuration setting (default, no descriptions included in search) for v3.7.2 rather than bumping to v3.8.0.
