### ISSUE TITLE
typo: moduled?

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#416]
https://github.com/lat9/ZCA-Bootstrap-Template/blob/4a2a2c09e0644122844cbfe97d40e3813e2b8472/includes/templates/bootstrap/templates/tpl_product_info_display.php#L308

**Comment by lat9** [comment]
It's been that way forever: https://github.com/lat9/ZCA-Bootstrap-Template/blob/519aadd5e0c534d035185e8dcd8c31e876408953/includes/templates/bootstrap/templates/tpl_product_info_display.php#L307

**Comment by torvista** [comment]
Sure, but now I guess it's going to irritate you!

**Comment by lat9** [comment]
No irritation, it's legacy.
