### ISSUE TITLE
AJAX search: Submitted keywords must be of type `string`

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#417]
... otherwise, logs result.  Unfortunately, I've nuked them.

**Comment by ms1225** [comment]
The below error is still persistent after implementing the fix:

`[14-Aug-2024 14:42:02 America/New_York] PHP Fatal error: Uncaught TypeError: zen_get_retail_or_wholesale_price(): Argument #2 ($wholesale_pricing_tier) must be of type string, null given, called in /includes/functions/functions_prices.php on line 468 and defined in /includes/functions/functions_prices.php:1637
Stack trace:
#0 /includes/functions/functions_prices.php(468): zen_get_retail_or_wholesale_price()
#1 /includes/functions/functions_prices.php(186): zen_get_products_base_price()
#2 /includes/classes/ajax/zcAjaxBootstrapSearch.php(65): zen_get_products_display_price()
#3 /ajax.php(72): zcAjaxBootstrapSearch->searchProducts()
#4 {main}
thrown in /includes/functions/functions_prices.php on line 1637`

The error occurs regardless of retail or wholesale customer logged in, or not logged in.
The error does not occur if the Ajax search is disabled.
