### ISSUE TITLE
CSS File version

### ISSUE THREAD

**Issue by scottcwilson** [lat9/ZCA-Bootstrap-Template#418]
The file `templates/bootstrap/css/stylesheet.css` indicates that the Bootstrap version is v3.4.0.  This a bit confusing since the actual version being used is 4.6.2 (per `html_header.php`).

**Comment by drbyte** [comment]
It's actually referring to the template-release-version when the file was last changed, not the bootstrap framework version.
Same pattern in most other files in this template.
Kinda like Zen Cart's version-stamping headers: only updated when file was last touched.

That said, I agree that it's slightly confusing that the descriptive text is merely "BOOTSTRAP" and not "BOOTSTRAP TEMPLATE".

**Comment by lat9** [comment]
FWIW, as I touch a file, I've been converting that older BOOTSTRAP x.y.z to Last updated: vx.y.z.

**Comment by scottcwilson** [comment]
Thanks!
