### ISSUE TITLE
Quantity entry on product listing page problems

### ISSUE THREAD

**Issue by daphilli224** [lat9/ZCA-Bootstrap-Template#442]
For certain browser window sizes, the number 0 (default value) in the quantity boxes on product listing pages partially or completely disappears. As the user reduces the size of the window, the size of the quantity box reduces until the left and right padding reduces and finally eliminates the space for the 0, making entry of a quantity to add to the cart from this screen difficult and/or confusing. For example, if the 0 does not show, entering a 1, makes the quantity 10. Reducing the window size further, moves the quantity box below the "Add:". See screenshots: window widths about 1163px and 1288px.

Possible fixes: (1) set the left and right padding to 0, and center the 0 or entry in the box, (2) set the quantity size box width to a fixed value, like the "Add:" box (i.e., don't let it reduce as the window size reduces, or (3) increase the point at which the quantity box moves below the "Add:" so the 0 or entered value is always visible.

<img width="613" alt="Window width about 1163px" src="https://github.com/user-attachments/assets/34a6b0aa-636f-409f-afd8-6ed13c976fad">
<img width="622" alt="Window width about 1288px" src="https://github.com/user-attachments/assets/c7a33eb5-60f4-4e9f-ad04-09c208624dfa">

**Comment by lat9** [comment]
Are the left/right sideboxes enabled? What are the settings for these bootstrap configuration values?
![image](https://github.com/user-attachments/assets/16c01b92-9332-4d32-b0a8-aa242404ae52)

... and where does that `(` in the quantity value come from?

**Comment by daphilli224** [comment]
Both sideboxes are enabled although not shown on the screen shots. The configuration values are 3, 6, and 3, for left column width, center column width, and right column width respectively. The “(“ in the quantity value is a “0” with the right half not visible because the space is inadequate to display the entire digit. The “0” is the default value for the field. I have not looked up specifically where it is set.

BTW, zc1.5.8a, php 8.2, bootstrap template version 3.7.3. 

Dave

**Comment by lat9** [comment]
Dave, could you either post a link or send me one via direct email or Zen Cart PM?  There haven't been changes in this area between 3.7.3 and 3.7.4-beta and I'm unable to reproduce your issue.

**Comment by lat9** [comment]
@daphilli224 pointed me in the right direction.  If, like the demo-products' "Documents" category, none of the products have specials the behavior noted in this issue arises.
