### ISSUE TITLE
Main page welcome greeting ignores setting in backend

### ISSUE THREAD

**Issue by retched** [lat9/ZCA-Bootstrap-Template#458]
A setting in ZenCart's backend decides whether the "Welcome to STORE_NAME" greeting is displayed on the front page. 

This setting is ignored as there isn't a check to see if it should be displayed. Currently, this means your only way of fixing it is hard deleting the line from `/includes/templates/bootstrap/templates/tpl_index_default.php` by force. or changing the $heading_title in the same manner.

I proposed PR #457 to change this behavior. The code will allow it to abide by the show greeting setting in the ZC backend but also allow the page to suggest an alternate title for screen readers.

**Comment by lat9** [comment]
What setting are you referring to?

**Comment by drbyte** [comment]
> What setting are you referring to?

From the linked PR description:
"This setting can be configured in the ZC Admin Backend under "Configuration > Layout Settings > Switch Customer Greeting > Show on Index" and Set to 0."

**Comment by lat9** [comment]
Yes, but that's for the customer greeting, not the page's **HEADING_TITLE**.

**Comment by retched** [comment]
That's my apologies then, I thought they were one in the same.

**Comment by lat9** [comment]
That's where this section comes in
https://github.com/lat9/ZCA-Bootstrap-Template/blob/ff53c70b6a668b95c95e0f46b9f47fc2c67449cd/includes/templates/bootstrap/templates/tpl_index_default.php#L32-L34
