### ISSUE TITLE
Configuration :: Product Listing :: Columns per row, display anomalies

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#47]
... as reported on the Zen Cart [support thread](https://www.zen-cart.com/showthread.php?223910-ZCA-Bootstrap-4-Template-Support-Thread&p=1377596#post1377596).

For some reason, having that value set to 3 (instead of the 0 I've been using) causes the listing displays to go _wonky_.

**Comment by drbyte** [comment]
Answered: https://www.zen-cart.com/showthread.php?223910-ZCA-Bootstrap-4-Template-Support-Thread&p=1377602#post1377602

Summary: use 0 with the bootstrap template.

**Comment by lat9** [comment]
Thanks, @drbyte.  I'll use the opportunity to create a FAQ article that starts with this.

**Comment by lat9** [comment]
Updated with a FAQ article with the information posted on the template's Zen Cart support-thread.
