### ISSUE TITLE
ZCA Bootstrap Colors configuration_group_id not passed to admin_pages

### ISSUE THREAD

**Issue by dbltoe** [lat9/ZCA-Bootstrap-Template#49]
Found with mod_list on all the latest 1.5.7c installs.
Mod list reports a "Missing Admin Configuration Page" for ZCA Bootstrap Colors on a standard 1.5.7c.
The configuration_group_id is created in the configuration_group table and the page_key value of toolsCZABootstrapColors is created in the admin_pages table but, the gID=## page_params is not propagated using the configuration_group_id.
Not sure that it affects actual operations but it does stop mod_list from accessing the admin page.

**Comment by drbyte** [comment]
It breaks pattern somewhat, insomuch as the actual editor for that group isn't on the configuration menu, but rather under the Tools menu (as denoted by the page_key prefix, and the menu_key).

**Comment by lat9** [comment]
Might be worth mentioning on the template's Zen Cart support thread (or in the one for Mod List, or both)?

**Comment by drbyte** [comment]
Or update the mod_list mod to check such anomalies against other menu_key categories where gID= is set.

**Comment by lat9** [comment]
> 
> 
> Or update the mod_list mod to check such anomalies against other menu_key categories where gID= is set.
That would be a 'good thing', since I use this construct in a couple of customizations.
