### ISSUE TITLE
Reduce 'footprint' of stylesheet_zca_colors.php

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#53]
Since those colors are 'pushed' as-is to the HTML output, reduce the footprint (i.e. number of bytes) associated with that output.

**Comment by dennisns7d** [comment]
Adjustments are needed in stylesheet_zca_colors.php:
- Line 75: Replace the leading space with '.'.
- Lines 96-99: Remove the trailing whitespace.

**Comment by lat9** [comment]
Thanks, @dennisns7d, for keeping me 'honest'!
