### ISSUE TITLE
Additional client stylesheet support

### ISSUE THREAD

**Issue by scottcwilson** [lat9/ZCA-Bootstrap-Template#68]
I have been adding a file called `includes/templates/bootstrap/css/client_styles.php` to bootstrap which is pulled in as follows: 

In `includes/templates/bootstrap/common/html_header.php`, right after the inclusion of stylesheet_zca_colors.php, 

```
    require($template->get_template_dir('client_styles.php', DIR_WS_TEMPLATE, $current_page_base, 'css') . '/client_styles.php');
```

Since it's pulled in last, it has the final word on styling.  This way, changes can be localized to this file, and the other 5 stylesheet_*.css files can be left unchanged. 

Let me know if you'd like this in a PR.

**Comment by lat9** [comment]
Just wondering why a `.php` instead of a `.css`?  Sounds like a good, forward-going change.

**Comment by scottcwilson** [comment]
To make it extra obvious that it's not an autoload file.

**Comment by scottcwilson** [comment]
Also, will get inlined so there's no need to clear cache to see the changes when you make them.

**Comment by scottcwilson** [comment]
If you assign to me I will do.

**Comment by dbltoe** [comment]
When using the changed html_header.php, it seems to break the requirement for the stylesheet_zca_colors.php
Tries finding it in the template_default vs bootstrap
`[17-Jan-2022 07:36:58 US/Central] Request URI: /, IP address: 216.177.186.199
#1 require() called at [/includes/templates/bootstrap/common/html_header.php:139]
#2 require(/includes/templates/bootstrap/common/html_header.php) called at [/index.php:42]
--> PHP Warning: require(includes/templates/template_default/css/stylesheet_zca_colors.php): failed to open stream: No such file or directory in /includes/templates/bootstrap/common/html_header.php on line 139.

[17-Jan-2022 07:36:58 US/Central] Request URI: /, IP address: 216.177.186.199
#1 require() called at [/includes/templates/bootstrap/common/html_header.php:139]
#2 require(/includes/templates/bootstrap/common/html_header.php) called at [/index.php:42]
--> PHP Warning: require(includes/templates/template_default/css/stylesheet_zca_colors.php): failed to open stream: No such file or directory in /includes/templates/bootstrap/common/html_header.php on line 139.

[17-Jan-2022 07:36:58 US/Central] PHP Fatal error: require(): Failed opening required 'includes/templates/template_default/css/stylesheet_zca_colors.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /includes/templates/bootstrap/common/html_header.php on line 139`

**Comment by scottcwilson** [comment]
I have made this exact mistake myself.  Putting in the `style` tags will prevent confusion.
