### ISSUE TITLE
Use Bootstrap $messageStack styling for "Place Order" shopping for message

### ISSUE THREAD

**Issue by scottcwilson** [lat9/ZCA-Bootstrap-Template#69]
Copy `includes/languages/english/responsive_classic/icon_names.php` and `includes/templates/responsive_classic/images/icons/*` to bootstrap to get newer icons.

**Comment by lat9** [comment]
On which pages?  I thought (!) that all those image-icons had been converted to use font-awesome glyphs in the Bootstrap template.

**Comment by scottcwilson** [comment]
I think this can only happen in very specific situations where the overrides you have done are not yet active.  As an example, go to Admin > Customers> Customers and press Place Order.   You'll see the message "Currently shopping for" ... with the old icon.

**Comment by lat9** [comment]
Oof, config.core.php doesn't provide any margin for inserting something in between the `$messageStack` instantiation and `init_customer_auth.php`, which is where that malformed message is issued.

As much as I hate it, let's go ahead with this change.  Let's be sure to mark that copy of the `icon_names.php` to indicate where it came from and note that the change is for BOOTSTRAP 3.1.3.

**Comment by scottcwilson** [comment]
We could hold on this and noodle some more if you want - the impact is much smaller than I thought because you generally use the FA stuff, as you pointed out.  I noticed the issue when testing Place Order and assumed it was for all icons.

**Comment by lat9** [comment]
I'll buy that ... I'm thinking that perhaps an observer action (when an EMP admin is logged in) to modify that message to use the FA stuff.

**Comment by scottcwilson** [comment]
who knows, we might could even get Chris to drop the use of this icon in this case?  I don't want to do something that you think junks up the template just for a silly edge case.

**Comment by scottcwilson** [comment]
You know, one way to fix this would simply be to change the core to:
- copy the icons from `./includes/templates/responsive_classic/images/icons/` into `./includes/templates/template_default/images/icons/` 
- change `includes/languages/english/icon_names.php` to refer to the .png files.

**Comment by lat9** [comment]
It would be more 'productive' to get `/includes/auto_loaders/config.core.php` to update its load points for `init_customer_auth.php`.
```
/**
 * Breakpoint 130.
 *
 * require('includes/init_includes/init_customer_auth.php');
 * messageStack = new messageStack();
 *
 */
  $autoLoadConfig[130][] = array('autoType'=>'classInstantiate',
                                 'className'=>'messageStack',
                                 'objectName'=>'messageStack');
  $autoLoadConfig[130][] = array('autoType'=>'init_script',
                                 'loadFile'=> 'init_customer_auth.php');
```
Changing the load point from 130 to 135 would enable the template's update to the messageStack to be registered prior to use by that script.

**Comment by scottcwilson** [comment]
I'm going to let you drive that one.  I think I will suggest changing to the .png images - people who build a template which is not based on responsive_classic still deserve newer and better images.

**Comment by drbyte** [comment]
Init load-order updated.
Ref: @lat9 comment above https://github.com/lat9/ZCA-Bootstrap-Template/issues/69#issuecomment-873151299

**Comment by scottcwilson** [comment]
Copied this fix to my 1.5.7 cart, tested Place Order, we get the 1.5.7 default .gif file (not the FA icon).  Is this what was intended? 

![Screen Shot 2021-07-03 at 2 44 40 PM](https://user-images.githubusercontent.com/4391638/124364104-50032100-dc0d-11eb-927b-898a432ebeca.jpg)

**Comment by lat9** [comment]
That's what's going to be shown until I get the Bootstrap template's update to move where the messageStack override is performed.

**Comment by lat9** [comment]
Give it another try with the change just posted.
