### ISSUE TITLE
Suggestion: Marquee for Bootstrap template

### ISSUE THREAD

**Issue by scottcwilson** [lat9/ZCA-Bootstrap-Template#70]
We could add a config (or perhaps a define page) and show a (non-empty) marquee message in `includes/templates/bootstrap/common/tpl_header.php`.

**Comment by lat9** [comment]
Usage examples?  I'm not prone to additional configuration settings, but could go on the presence/absence of some definition.

**Comment by scottcwilson** [comment]
Like I said, you could use a define file instead of a config.  Usage:

This July 4th, the store will be closed. Happy Independence Day!

**Comment by lat9** [comment]
Noting that this could be accomplished with a site-specific `init_include` that sets the associated message for the site's header or via the Banner Manager, which has the extra-added benefit that the message can be 'scheduled':
![image](https://user-images.githubusercontent.com/2685585/124610989-04d05480-de3f-11eb-9f32-e8449d6104dc.png)

The display looks similar to:
![image](https://user-images.githubusercontent.com/2685585/124611085-1d406f00-de3f-11eb-9221-b218aad95f6f.png)

**Comment by scottcwilson** [comment]
Excellent ideas!  Do you want to put that in the help?
