### ISSUE TITLE
back-to-top covers continue button in checkout

### ISSUE THREAD

**Issue by scottcwilson** [lat9/ZCA-Bootstrap-Template#76]
<img width="637" alt="back_to_top" src="https://user-images.githubusercontent.com/4391638/128009089-7f49f7ca-a23d-49bb-8535-fd355b47b85e.png">

A couple of things I have done to mitigate this; not sure which is best:

1. edit `includes/templates/bootstrap/common/tpl_main_page.php`
and wrap
```
<a href="#" id="back-to-top" ...
```
in a page check like: 
```
<?php if (!in_array($current_page_base, explode(',','shopping_cart,checkout_shipping,checkout_shipping_address,checkout_payment,checkout_payment_address,checkout_confirmation,checkout_success'))) { ?>
```

2. Edit `includes/templates/bootstrap/css/stylesheet.css` and change `#back-to-top` styling to use 

```
     bottom: 100px;
```

**Comment by lat9** [comment]
FWIW, that's a simple update to the stylesheet, moving the back-to-top link further up the side of the page.
