### ISSUE TITLE
css is missing .forward class 

### ISSUE THREAD

**Issue by scottcwilson** [lat9/ZCA-Bootstrap-Template#80]
Just add 
```
.forward {float:right;}
```
to includes/templates/bootstrap/css/stylesheet.css

This will fix the problem shown in this image on the checkout success page: 

<img width="947" alt="checkout_success" src="https://user-images.githubusercontent.com/4391638/128603161-93f41d53-b3a6-4916-8398-c7f96d00eeeb.png">

**Comment by lat9** [comment]
Might as well add `.back {float: left;}` too.
