### ISSUE TITLE
JS error on the address book process page because #stBreak element is missing

### ISSUE THREAD

**Issue by marco-pm** [lat9/ZCA-Bootstrap-Template#97]
```
index.php?main_page=address_book_process&edit=1:720 Uncaught TypeError: Cannot set properties of null (setting 'className')
    at hideStateField (index.php?main_page=address_book_process&edit=1:720)
    at update_zone (index.php?main_page=address_book_process&edit=1:423)
    at onload (index.php?main_page=address_book_process&edit=1:888)
```

This is because the bootstrap template doesn't include the `stBreak` element, and in the ZC script `jscript_addr_pulldowns.php` (under `address_book_process`) there is no check that `stBreak` actually exists on the page (unlike `stText`):

```
    if (document.getElementById("stText")) {
      document.getElementById("stText").className = 'hiddenField';
      document.getElementById("stText").setAttribute('className', 'hiddenField');
    }
    document.getElementById("stBreak").className = 'hiddenField';
    document.getElementById("stBreak").setAttribute('className', 'hiddenField');
```

I would therefore add it somewhere, e.g. in `tpl_address_book_process_default.php`, with `d-none` class, so that the js error is not thrown. Of course the ideal solution would be to add the check in the ZC core js file.

**Comment by lat9** [comment]
Noting that the change is made to `tpl_modules_common_address_format.php` so that the issue gets squished for the create-account and multi-page checkout pages' processing, too.
