### ISSUE TITLE
Adding a modal AJAX-search option, create Bootstrap configuration settings group

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#99]
... as an enhancement.  This change will also 'migrate' all template-specific configuration settings to a common (Bootstrap Template Settings) configuration group.

**Comment by torvista** [comment]
Conceptually, how would I go about using the ajax search from the non-modal/fixed search box?

**Comment by lat9** [comment]
That's going to require changes to the associated AJAX class, (possibly) the template that forms the output and probably the jQuery that watches for the search-terms' entry (depending on whether/not you change the associated selectors).
